volumes:
  database_volume:

services:
  db:
    image: postgres:17.4
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5433
    ports:
      - 15433:5433

  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: bash -c "npm install && npm start"

  frontend:
    image: node:lts-bullseye
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_HOST: http://localhost:8000
      BASE_URL: http://localhost:5173
      HOST: 0.0.0.0
    ports:
      - "5173:5173"
