version: "3.8"

volumes:
  database_volume:

services:
  db:
    image: postgres:17.4
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGPORT=${DB_PORT}
    ports:
      - 15433:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: backend
    command: pnpm run --filter=backend start
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /app/backend/node_modules/
      - ./backend:/app/backend
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}

  frontend:
    build:
      context: .
      target: frontend
    command: pnpm run --filter=frontend start
    volumes:
      - /app/frontend/node_modules/
      - ./frontend:/app/frontend
    ports:
      - 5173:5173
    env_file: .env
