version: "3.8"

volumes:
  database_volume:

services:
  db:
    image: postgres:17.4
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 15432:5432

  backend:
    build:
      context: .
      target: backend
    command: pnpm run --filter=backend start
    volumes:
      - /app/backend/node_modules/
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENV}
