version: "3.8"

volumes:
  database_volume:

services:
  db:
    image: postgres:17.4
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGPORT=${DB_PORT}
    ports:
      - 15433:${DB_PORT}

  backend:
    build:
      context: .
      target: backend
    command: pnpm run --filter=backend start
    volumes:
      - /app/backend/node_modules/
      - ./backend:/app/backend
    ports:
      - 8000:8000
    env_file: .env

  frontend:
    build:
      context: .
      target: frontend
    command: pnpm run --filter=frontend start
    volumes:
      - /app/frontend/node_modules/
      - ./frontend:/app/frontend
    ports:
      - 5173:5173
    env_file: .env
