name: Code Check
on:
  # push: # TODO test on push before making pr
  pull_request:
    branches: [$default-branch]

# Cancel this code check if a newer commit on the branch is in the queue
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Determine whether to run checks on FE and/or BE components
  setup:
    runs-on: ubuntu-latest
    outputs:
      changes:
    steps:
      - name: Check changed directories
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**/*.js'
              - 'backend/**/*.jsx'
              - 'backend/**/*.ts'
              - 'backend/**/*.tsx'
              - 'backend/**/*.json'
            frontend:
              - 'frontend/**/*.js'
              - 'frontend/**/*.jsx'
              - 'frontend/**/*.ts'
              - 'frontend/**/*.tsx'
              - 'frontend/**/*.json'
              - 'frontend/**/*.css'

  lint:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.changes.frontend == 'true' || needs.setup.outputs.changes.backend == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
            backend
            biome.json
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci

  tsc-typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run 'tsc' on FE
        if: ${{ needs.setup.outputs.changes.frontend == 'true' }}
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          workdir: frontend
          filter_mode: nofilter
          fail_on_error: true
      - name: Run 'tsc' on BE
        if: ${{ needs.setup.outputs.changes.backend == 'true' }}
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          workdir: backend
          filter_mode: nofilter
          fail_on_error: true
